// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wedstrijdplannenmvc.Models;

namespace wedstrijdplannenmvc.Migrations
{
    [DbContext(typeof(CompetitieContext))]
    [Migration("20210910115146_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("wedstrijdplannenmvc.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doelpuntentegen")
                        .HasColumnType("int");

                    b.Property<int>("doelpuntenvoor")
                        .HasColumnType("int");

                    b.Property<int>("doelsaldo")
                        .HasColumnType("int");

                    b.Property<int>("punten")
                        .HasColumnType("int");

                    b.Property<int>("wedstrijdengespeeld")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("wedstrijdplannenmvc.Models.TeamWedstrijd", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("WedstrijdId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "WedstrijdId");

                    b.HasIndex("WedstrijdId");

                    b.ToTable("TeamWedstrijd");
                });

            modelBuilder.Entity("wedstrijdplannenmvc.Models.Wedstrijd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("thuisteam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thuisteamuitslag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uitteamuitslag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wedstrijden");
                });

            modelBuilder.Entity("wedstrijdplannenmvc.Models.TeamWedstrijd", b =>
                {
                    b.HasOne("wedstrijdplannenmvc.Models.Team", "team")
                        .WithMany("TeamWedstrijd")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wedstrijdplannenmvc.Models.Wedstrijd", "Westrijd")
                        .WithMany("teamwedstrijd")
                        .HasForeignKey("WedstrijdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("team");

                    b.Navigation("Westrijd");
                });

            modelBuilder.Entity("wedstrijdplannenmvc.Models.Team", b =>
                {
                    b.Navigation("TeamWedstrijd");
                });

            modelBuilder.Entity("wedstrijdplannenmvc.Models.Wedstrijd", b =>
                {
                    b.Navigation("teamwedstrijd");
                });
#pragma warning restore 612, 618
        }
    }
}
